// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/analytics/ActivityTicker.tsx": () => import("../components/mockups/analytics/ActivityTicker.tsx"),
  "./components/mockups/analytics/GrowthChart.tsx": () => import("../components/mockups/analytics/GrowthChart.tsx"),
  "./components/mockups/analytics/StatsWidget.tsx": () => import("../components/mockups/analytics/StatsWidget.tsx")
};
